In [1]:
# Import necessary libraries
import numpy as np
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import r2_score

In [2]:
# Load the dataset
retail_metadata = pd.read_csv("retail_metadata.csv")  
retail_metadata.head(10)

InvoiceNo StockCode                          Description  Quantity  \
0     536365    85123A   WHITE HANGING HEART T-LIGHT HOLDER         6   
1     536365     71053                  WHITE METAL LANTERN         6   
2     536365    84406B       CREAM CUPID HEARTS COAT HANGER         8   
3     536365    84029G  KNITTED UNION FLAG HOT WATER BOTTLE         6   
4     536365    84029E       RED WOOLLY HOTTIE WHITE HEART.         6   
5     536365     22752         SET 7 BABUSHKA NESTING BOXES         2   
6     536365     21730    GLASS STAR FROSTED T-LIGHT HOLDER         6   
7     536366     22633               HAND WARMER UNION JACK         6   
8     536366     22632            HAND WARMER RED POLKA DOT         6   
9     536367     84879        ASSORTED COLOUR BIRD ORNAMENT        32   

           InvoiceDate  UnitPrice  CustomerID         Country      Time  \
0  2010-12-01 08:26:00       2.55     17850.0  United Kingdom  08:26:00   
1  2010-12-01 08:26:00       3.39     17850.0  United Kingdom  08:26:00   
2  2010-12-01 08:26:00       2.75     17850.0  United Kingdom  08:26:00   
3  2010-12-01 08:26:00       3.39     17850.0  United Kingdom  08:26:00   
4  2010-12-01 08:26:00       3.39     17850.0  United Kingdom  08:26:00   
5  2010-12-01 08:26:00       7.65     17850.0  United Kingdom  08:26:00   
6  2010-12-01 08:26:00       4.25     17850.0  United Kingdom  08:26:00   
7  2010-12-01 08:28:00       1.85     17850.0  United Kingdom  08:28:00   
8  2010-12-01 08:28:00       1.85     17850.0  United Kingdom  08:28:00   
9  2010-12-01 08:34:00       1.69     13047.0  United Kingdom  08:34:00   

      Month        Day  Year  Total Amount  
0  December  Wednesday  2010         15.30  
1  December  Wednesday  2010         20.34  
2  December  Wednesday  2010         22.00  
3  December  Wednesday  2010         20.34  
4  December  Wednesday  2010         20.34  
5  December  Wednesday  2010         15.30  
6  December  Wednesday  2010         25.50  
7  December  Wednesday  2010         11.10  
8  December  Wednesday  2010         11.10  
9  December  Wednesday  2010         54.08

In [3]:
retail_metadata["Country"].value_counts()

Country
United Kingdom          349227
Germany                   9027
France                    8327
EIRE                      7228
Spain                     2480
Netherlands               2363
Belgium                   2031
Switzerland               1842
Portugal                  1453
Australia                 1184
Norway                    1072
Italy                      758
Channel Islands            747
Finland                    685
Cyprus                     603
Sweden                     450
Austria                    398
Denmark                    380
Poland                     330
Japan                      321
Israel                     245
Unspecified                241
Singapore                  222
Iceland                    182
USA                        179
Canada                     151
Greece                     145
Malta                      112
United Arab Emirates        68
European Community          60
RSA                         58
Lebanon                     45


In [4]:
retail_metadata[retail_metadata["Country"] == "Australia"]

InvoiceNo StockCode                          Description  Quantity  \
195        536389     22941         CHRISTMAS LIGHTS 10 REINDEER         6   
196        536389     21622     VINTAGE UNION JACK CUSHION COVER         8   
197        536389     21791   VINTAGE HEADS AND TAILS CARD GAME         12   
198        536389    35004C      SET OF 3 COLOURED  FLYING DUCKS         6   
199        536389    35004G           SET OF 3 GOLD FLYING DUCKS         4   
...           ...       ...                                  ...       ...   
362409     578459     22086      PAPER CHAIN KIT 50'S CHRISTMAS         20   
362410     578459     22340           NOEL GARLAND PAINTED ZINC         24   
362411     578459     22576  SWALLOW WOODEN CHRISTMAS DECORATION        20   
362412     578459     22580         ADVENT CALENDAR GINGHAM SACK        12   
362413     578459     22669                    RED BABY BUNTING         12   

                InvoiceDate  UnitPrice  CustomerID    Country      Time  \
195     2010-12-01 10:03:00       8.50     12431.0  Australia  10:03:00   
196     2010-12-01 10:03:00       4.95     12431.0  Australia  10:03:00   
197     2010-12-01 10:03:00       1.25     12431.0  Australia  10:03:00   
198     2010-12-01 10:03:00       5.45     12431.0  Australia  10:03:00   
199     2010-12-01 10:03:00       6.35     12431.0  Australia  10:03:00   
...                     ...        ...         ...        ...       ...   
362409  2011-11-24 12:30:00       2.95     12388.0  Australia  12:30:00   
362410  2011-11-24 12:30:00       0.39     12388.0  Australia  12:30:00   
362411  2011-11-24 12:30:00       0.85     12388.0  Australia  12:30:00   
362412  2011-11-24 12:30:00       5.95     12388.0  Australia  12:30:00   
362413  2011-11-24 12:30:00       2.95     12388.0  Australia  12:30:00   

           Month        Day  Year  Total Amount  
195     December  Wednesday  2010         51.00  
196     December  Wednesday  2010         39.60  
197     December  Wednesday  2010         15.00  
198     December  Wednesday  2010         32.70  
199     December  Wednesday  2010         25.40  
...          ...        ...   ...           ...  
362409  November   Thursday  2011         59.00  
362410  November   Thursday  2011          9.36  
362411  November   Thursday  2011         17.00  
362412  November   Thursday  2011         71.40  
362413  November   Thursday  2011         35.40  

[1184 rows x 13 columns]

In [5]:
retail_metadata.shape

(392732, 13)

In [6]:
retail_metadata.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 392732 entries, 0 to 392731
Data columns (total 13 columns):
 #   Column        Non-Null Count   Dtype  
---  ------        --------------   -----  
 0   InvoiceNo     392732 non-null  int64  
 1   StockCode     392732 non-null  object 
 2   Description   392732 non-null  object 
 3   Quantity      392732 non-null  int64  
 4   InvoiceDate   392732 non-null  object 
 5   UnitPrice     392732 non-null  float64
 6   CustomerID    392732 non-null  float64
 7   Country       392732 non-null  object 
 8   Time          392732 non-null  object 
 9   Month         392732 non-null  object 
 10  Day           392732 non-null  object 
 11  Year          392732 non-null  int64  
 12  Total Amount  392732 non-null  float64
dtypes: float64(3), int64(3), object(7)
memory usage: 39.0+ MB


In [7]:
retail_stock_sales = retail_metadata.groupby(['Country','StockCode'])[['Quantity','UnitPrice','Total Amount']].sum().reset_index()
retail_stock_sales

Country StockCode  Quantity  UnitPrice  Total Amount
0        Australia     15036       600       0.72        432.00
1        Australia   15056BL         3       5.95         17.85
2        Australia    16161P       400       0.34        136.00
3        Australia    16169E        25       0.42         10.50
4        Australia     20665         6       2.95         17.70
...            ...       ...       ...        ...           ...
18932  Unspecified    85179C         1       4.65          4.65
18933  Unspecified    85180A         2       4.65          9.30
18934  Unspecified    85180B         1       4.65          4.65
18935  Unspecified     85212        12       0.29          3.48
18936  Unspecified     85213        12       0.29          3.48

[18937 rows x 5 columns]

In [8]:
retail_stock_sales.to_csv('retail_stock_sales.csv',index=False)

In [9]:
retail_stock_max = retail_stock_sales.groupby(['Country','StockCode'])['Quantity'].sum().reset_index()
retail_stock_max.max()

Country      Unspecified
StockCode           POST
Quantity           80995
dtype: object

In [10]:
retail_stock_min = retail_stock_sales.groupby(['Country','StockCode'])['UnitPrice'].sum().reset_index()
retail_stock_min.min()

Country      Australia
StockCode        10002
UnitPrice          0.0
dtype: object

In [11]:
retail_stock_sales['StockCode'].values

array(['15036', '15056BL', '16161P', ..., '85180B', '85212', '85213'],
      dtype=object)

In [12]:
retail_metadata[retail_metadata['StockCode'] == "15036"].groupby('Country')[['Quantity','UnitPrice','Total Amount']].sum().reset_index()

Country  Quantity  UnitPrice  Total Amount
0       Australia       600       0.72        432.00
1         Denmark        12       0.83          9.96
2            EIRE        48       2.49         39.84
3          France        60       2.41         48.84
4         Germany      1164       7.13        853.32
5           Italy        12       0.75          9.00
6     Netherlands        12       0.83          9.96
7          Norway        48       0.83         39.84
8          Sweden       804       2.30        587.16
9  United Kingdom     19116     243.34      14014.52

In [13]:
retail_stock_sales['Country'].unique()

array(['Australia', 'Austria', 'Bahrain', 'Belgium', 'Brazil', 'Canada',
       'Channel Islands', 'Cyprus', 'Czech Republic', 'Denmark', 'EIRE',
       'European Community', 'Finland', 'France', 'Germany', 'Greece',
       'Iceland', 'Israel', 'Italy', 'Japan', 'Lebanon', 'Lithuania',
       'Malta', 'Netherlands', 'Norway', 'Poland', 'Portugal', 'RSA',
       'Saudi Arabia', 'Singapore', 'Spain', 'Sweden', 'Switzerland',
       'USA', 'United Arab Emirates', 'United Kingdom', 'Unspecified'],
      dtype=object)

In [14]:
encoder = LabelEncoder()
encoded_retail_stock = retail_stock_sales.copy()
encoded_retail_stock['Country'] = encoder.fit_transform(encoded_retail_stock['Country'])
pd.unique(encoded_retail_stock['Country'])


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36])

In [15]:
encoded_retail_stock['StockCode'].value_counts()

StockCode
22423     29
22960     25
22961     25
23240     24
POST      23
          ..
35809B     1
35816P     1
35817P     1
35818B     1
PADS       1
Name: count, Length: 3665, dtype: int64

In [16]:
encoded_retail_stock['StockCode'].values[1531]

'23344'

In [17]:
encoder = LabelEncoder()
encoded_retail_stock['StockCode'] = encoder.fit_transform(encoded_retail_stock['StockCode'])
encoded_retail_stock['StockCode'].value_counts()

StockCode
1288    29
1801    25
1802    25
2070    24
3664    23
        ..
2442     1
2446     1
2447     1
2448     1
3663     1
Name: count, Length: 3665, dtype: int64

In [18]:
encoded_retail_stock.corr()

Country  StockCode  Quantity  UnitPrice  Total Amount
Country       1.000000   0.067959  0.189456   0.186493      0.177557
StockCode     0.067959   1.000000 -0.009250   0.034781      0.012405
Quantity      0.189456  -0.009250  1.000000   0.278587      0.781681
UnitPrice     0.186493   0.034781  0.278587   1.000000      0.618024
Total Amount  0.177557   0.012405  0.781681   0.618024      1.000000

In [19]:
# Model Training
X = encoded_retail_stock.drop(columns=["Total Amount"])
y = encoded_retail_stock['Total Amount']

In [20]:
X

Country  StockCode  Quantity  UnitPrice
0            0         12       600       0.72
1            0         18         3       5.95
2            0         46       400       0.34
3            0         51        25       0.42
4            0        130         6       2.95
...        ...        ...       ...        ...
18932       36       3288         1       4.65
18933       36       3289         2       4.65
18934       36       3290         1       4.65
18935       36       3318        12       0.29
18936       36       3319        12       0.29

[18937 rows x 4 columns]

In [21]:
y

0        432.00
1         17.85
2        136.00
3         10.50
4         17.70
          ...  
18932      4.65
18933      9.30
18934      4.65
18935      3.48
18936      3.48
Name: Total Amount, Length: 18937, dtype: float64

In [22]:
# Split the data into training and testing sets (80% train, 20% test)
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=350)

In [23]:
print(X.shape,X_train.shape,X_test.shape)

(18937, 4) (13255, 4) (5682, 4)


In [24]:
model = RandomForestRegressor(n_estimators=100, random_state=42)
model.fit(X_train, y_train)

RandomForestRegressor(random_state=42)

In [25]:
# Model Evaluation
y_pred = model.predict(X_test)
y_pred

array([ 15.3   ,  17.    , 390.5945, ...,  15.    ,  74.1379,  19.8   ])

In [26]:
mae = mean_absolute_error(y_test, y_pred)
print("Mean Absolute Error:", mae)

Mean Absolute Error: 104.26184137099612


In [27]:
R2_score = r2_score(y_test,y_pred)
print("R2 score for your model is :",R2_score)

R2 score for your model is : 0.9173893757923063


### Building The Predictive System

In [34]:
X_test.values[1410]

array([  34.  , 1847.  ,    6.  ,   14.95])

In [35]:
stock_value = X_test.values[1410].reshape(1,-1)

In [36]:
prediction = model.predict(stock_value)
print("Total Amount for your StockCode 2322. in 14. Country is :", prediction[0])

Total Amount for your StockCode 2322. in 14. Country is : 85.6079999999999


C:\Users\Admin\Desktop\Anaconda\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but RandomForestRegressor was fitted with feature names
  warnings.warn(


In [37]:
y_test.values[1410]

89.69999999999999

### Creating a pickle file

In [38]:
import pickle as pkl
file_name = 'Countrywise_Product_Sales.sav'
pkl.dump(model,open(file_name,'wb'))

In [33]:
encoded_retail_stock.to_csv('encoded_retail_stock.csv',index=False)